# Funding links for this project
# Maintainer: Luke Steuber - lukesteuber.com

github: lukeslp
patreon: lukeslp
custom:
  - https://usefulai.lemonsqueezy.com/buy/bf6ce1bd-85f5-4a09-ba10-191a670f74af
  - https://assisted.site/
