package:
  name: llamaline
  version: "1.0.2"

source:
  url: https://files.pythonhosted.org/packages/source/l/llamaline/llamaline-1.0.2.tar.gz
  sha256: 7ba8d961750215fcefba7e9fd749afd7406e94fa01054810eb4986591671cf48

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - llamaline = llamaline.llamaline:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - colorama
    - rich
    - requests

test:
  imports:
    - llamaline
  commands:
    - llamaline --help

about:
  home: https://github.com/lukeslp/llamaline
  dev_url: https://github.com/lukeslp/llamaline
  doc_url: https://github.com/lukeslp/llamaline#readme
  license: MIT
  license_family: MIT

  summary: "A natural-language to shell/Python CLI assistant using local Ollama models."
  description: |
    llamaline transforms everyday tasks into simple English commands! 
    It bridges the gap between natural language and code execution, 
    making command-line operations accessible to everyone with comprehensive 
    safety features and accessibility support.
  author: "Luke Steuber"
  author_email: "luke@lukesteuber.com"

extra:
  recipe-maintainers:
    - lukeslp